server:
  port: 8080

spring:
  config:
    import:
      - database.properties
      - api.properties
      - jwt.properties
      - cors.properties

  datasource:
    url: ${DB.URL}
    username: ${DB.USERNAME}
    password: ${DB.PASSWORD}
    driver-class-name: ${DB.DRIVER}
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    database-platform: ${DB.DIALECT}
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        physical_naming_strategy: ${DB.NAMING_STRATEGY}