server:
  port: 8080

spring:
  devtools:
    restart:
      enabled: true

  config:
    import:
      - database.properties
      - api.properties
      - jwt.properties
      - s3.properties
      - redis.properties

  jackson:
    time-zone: Asia/Seoul

  datasource:
    url: ${DB.URL}
    username: ${DB.USERNAME}
    password: ${DB.PASSWORD}
    driver-class-name: ${DB.DRIVER}
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:none}
    database-platform: ${DB.DIALECT}
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        show_sql: true
        format_sql: true
        physical_naming_strategy: ${DB.NAMING_STRATEGY}
  cloud:
    aws:
      credentials:
        access-key: ${S3.ACCESS_KEY}
        secret-key: ${S3.SECRET_KEY}
      region:
        static: ${S3.REGION}
      s3:
        bucket: ${S3.BUCKET}
      stack:
        auto: false
  data:
    redis:
      host: ${REDIS.HOST}
      port: ${REDIS.PORT}
      timeout: ${REDIS.TIMEOUT}
      lettuce:
        pool:
          max-active: ${REDIS.MAX_ACTIVE}
          max-idle: ${REDIS.MAX_IDLE}
          min-idle: ${REDIS.MIN_IDLE}
          max-wait: ${REDIS.MAX_WAIT}
        shutdown-timeout: ${REDIS.SHUTDOWN_TIMEOUT}

logging:
  level:
    com.ssafy.solvedpick: ${LOG_LEVEL:DEBUG}
